[versions]
kotlin = "2.3.21"
scala = "3.8.3"
jspecify = "1.0.0"
jackson = "2.17.0"
classgraph = "4.8.179"
junit = "5.12.2"
spotless = "8.6.0"
palantir-java-format = "2.91.0"
scalafmt = "3.11.1"
errorprone = "2.49.0"
errorprone-plugin = "5.1.0"
errorprone-support = "0.29.0"
nullaway = "0.13.4"
nullaway-plugin = "3.0.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
scala-library = { module = "org.scala-lang:scala3-library_3", version.ref = "scala" }
scalatest = { module = "org.scalatest:scalatest_3", version = "3.2.19" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-contrib = { module = "tech.picnic.error-prone-support:error-prone-contrib", version.ref = "errorprone-support" }
errorprone-refaster = { module = "tech.picnic.error-prone-support:refaster-runner", version.ref = "errorprone-support" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
japicmp = { id = "me.champeau.gradle.japicmp", version = "0.4.6" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
palantir-java-format-idea = { id = "com.palantir.java-format-idea", version.ref = "palantir-java-format" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullaway-plugin" }
